// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResolutionManagement.Data;

#nullable disable

namespace ResolutionManagement.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ResolutionManagement.Models.FeedbackRequest", b =>
                {
                    b.Property<int?>("FeedbackRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("FeedbackRequestId"), 1L, 1);

                    b.Property<bool?>("Accepted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ESignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResolutionId")
                        .HasColumnType("int");

                    b.Property<bool?>("Resolved")
                        .HasColumnType("bit");

                    b.HasKey("FeedbackRequestId");

                    b.HasIndex("ResolutionId");

                    b.ToTable("FeedbackRequest", (string)null);

                    b.HasData(
                        new
                        {
                            FeedbackRequestId = 0,
                            Accepted = false,
                            CreationDate = new DateTime(2022, 10, 5, 20, 16, 37, 620, DateTimeKind.Local).AddTicks(2007),
                            Description = "This sounds like a good proposal",
                            ESignature = "bob jones",
                            OwnerUserID = "37c1ba03-d67c-437e-ac19-2b38b123c55a",
                            ResolutionId = 0,
                            Resolved = true
                        },
                        new
                        {
                            FeedbackRequestId = 1,
                            Accepted = true,
                            CreationDate = new DateTime(2022, 10, 5, 20, 16, 37, 620, DateTimeKind.Local).AddTicks(2013),
                            Description = "This sounds like a good proposal",
                            ESignature = "bob jones",
                            OwnerUserID = "221fedc9-3ad4-492e-bfc0-20f198923a24",
                            ResolutionId = 0,
                            Resolved = true
                        },
                        new
                        {
                            FeedbackRequestId = 2,
                            Accepted = false,
                            CreationDate = new DateTime(2022, 10, 5, 20, 16, 37, 620, DateTimeKind.Local).AddTicks(2015),
                            Description = "I have this proposal",
                            ESignature = "jane doe",
                            OwnerUserID = "d34e5684-030b-4bf1-ba0b-51c424468294",
                            ResolutionId = 0,
                            Resolved = true
                        },
                        new
                        {
                            FeedbackRequestId = 3,
                            Accepted = true,
                            CreationDate = new DateTime(2022, 10, 5, 20, 16, 37, 620, DateTimeKind.Local).AddTicks(2018),
                            Description = "Sounds good",
                            ESignature = "Shawn Kal",
                            OwnerUserID = "c5955b95-5492-4c7b-a3cb-c749c85e3a16",
                            ResolutionId = 0,
                            Resolved = true
                        },
                        new
                        {
                            FeedbackRequestId = 4,
                            Accepted = true,
                            CreationDate = new DateTime(2022, 10, 5, 20, 16, 37, 620, DateTimeKind.Local).AddTicks(2021),
                            Description = "i like this",
                            ESignature = "Emily Low",
                            OwnerUserID = "5559d343-5062-4cd1-b0ae-25301e70a10d",
                            ResolutionId = 0,
                            Resolved = true
                        },
                        new
                        {
                            FeedbackRequestId = 5,
                            Accepted = false,
                            CreationDate = new DateTime(2022, 10, 5, 20, 16, 37, 620, DateTimeKind.Local).AddTicks(2026),
                            Description = "",
                            ESignature = "",
                            OwnerUserID = "37c1ba03-d67c-437e-ac19-2b38b123c55a",
                            ResolutionId = 1,
                            Resolved = false
                        },
                        new
                        {
                            FeedbackRequestId = 6,
                            Accepted = false,
                            CreationDate = new DateTime(2022, 10, 5, 20, 16, 37, 620, DateTimeKind.Local).AddTicks(2029),
                            Description = "",
                            ESignature = "",
                            OwnerUserID = "221fedc9-3ad4-492e-bfc0-20f198923a24",
                            ResolutionId = 1,
                            Resolved = false
                        },
                        new
                        {
                            FeedbackRequestId = 7,
                            Accepted = false,
                            CreationDate = new DateTime(2022, 10, 5, 20, 16, 37, 620, DateTimeKind.Local).AddTicks(2031),
                            Description = "",
                            ESignature = "",
                            OwnerUserID = "d34e5684-030b-4bf1-ba0b-51c424468294",
                            ResolutionId = 1,
                            Resolved = false
                        },
                        new
                        {
                            FeedbackRequestId = 8,
                            Accepted = false,
                            CreationDate = new DateTime(2022, 10, 5, 20, 16, 37, 620, DateTimeKind.Local).AddTicks(2034),
                            Description = "",
                            ESignature = "",
                            OwnerUserID = "c5955b95-5492-4c7b-a3cb-c749c85e3a16",
                            ResolutionId = 1,
                            Resolved = false
                        },
                        new
                        {
                            FeedbackRequestId = 9,
                            Accepted = false,
                            CreationDate = new DateTime(2022, 10, 5, 20, 16, 37, 620, DateTimeKind.Local).AddTicks(2038),
                            Description = "",
                            ESignature = "",
                            OwnerUserID = "5559d343-5062-4cd1-b0ae-25301e70a10d",
                            ResolutionId = 1,
                            Resolved = false
                        },
                        new
                        {
                            FeedbackRequestId = 10,
                            Accepted = true,
                            CreationDate = new DateTime(2022, 10, 5, 20, 16, 37, 620, DateTimeKind.Local).AddTicks(2040),
                            Description = "This sounds like a good proposal",
                            ESignature = "bob jones",
                            OwnerUserID = "37c1ba03-d67c-437e-ac19-2b38b123c55a",
                            ResolutionId = 2,
                            Resolved = true
                        },
                        new
                        {
                            FeedbackRequestId = 11,
                            Accepted = true,
                            CreationDate = new DateTime(2022, 10, 5, 20, 16, 37, 620, DateTimeKind.Local).AddTicks(2043),
                            Description = "This sounds like a good proposal",
                            ESignature = "bob jones",
                            OwnerUserID = "221fedc9-3ad4-492e-bfc0-20f198923a24",
                            ResolutionId = 2,
                            Resolved = true
                        },
                        new
                        {
                            FeedbackRequestId = 12,
                            Accepted = false,
                            CreationDate = new DateTime(2022, 10, 5, 20, 16, 37, 620, DateTimeKind.Local).AddTicks(2091),
                            Description = "I hate this proposal",
                            ESignature = "jane doe",
                            OwnerUserID = "d34e5684-030b-4bf1-ba0b-51c424468294",
                            ResolutionId = 2,
                            Resolved = true
                        },
                        new
                        {
                            FeedbackRequestId = 13,
                            Accepted = false,
                            CreationDate = new DateTime(2022, 10, 5, 20, 16, 37, 620, DateTimeKind.Local).AddTicks(2094),
                            Description = "",
                            ESignature = "",
                            OwnerUserID = "c5955b95-5492-4c7b-a3cb-c749c85e3a16",
                            ResolutionId = 2,
                            Resolved = false
                        },
                        new
                        {
                            FeedbackRequestId = 14,
                            Accepted = false,
                            CreationDate = new DateTime(2022, 10, 5, 20, 16, 37, 620, DateTimeKind.Local).AddTicks(2097),
                            Description = "",
                            ESignature = "",
                            OwnerUserID = "5559d343-5062-4cd1-b0ae-25301e70a10d",
                            ResolutionId = 2,
                            Resolved = false
                        },
                        new
                        {
                            FeedbackRequestId = 15,
                            Accepted = false,
                            CreationDate = new DateTime(2022, 10, 5, 20, 16, 37, 620, DateTimeKind.Local).AddTicks(2100),
                            Description = "",
                            ESignature = "",
                            OwnerUserID = "37c1ba03-d67c-437e-ac19-2b38b123c55a",
                            ResolutionId = 3,
                            Resolved = false
                        },
                        new
                        {
                            FeedbackRequestId = 16,
                            Accepted = false,
                            CreationDate = new DateTime(2022, 10, 5, 20, 16, 37, 620, DateTimeKind.Local).AddTicks(2103),
                            Description = "",
                            ESignature = "",
                            OwnerUserID = "221fedc9-3ad4-492e-bfc0-20f198923a24",
                            ResolutionId = 3,
                            Resolved = false
                        },
                        new
                        {
                            FeedbackRequestId = 17,
                            Accepted = false,
                            CreationDate = new DateTime(2022, 10, 5, 20, 16, 37, 620, DateTimeKind.Local).AddTicks(2107),
                            Description = "",
                            ESignature = "",
                            OwnerUserID = "d34e5684-030b-4bf1-ba0b-51c424468294",
                            ResolutionId = 3,
                            Resolved = false
                        },
                        new
                        {
                            FeedbackRequestId = 18,
                            Accepted = false,
                            CreationDate = new DateTime(2022, 10, 5, 20, 16, 37, 620, DateTimeKind.Local).AddTicks(2109),
                            Description = "",
                            ESignature = "",
                            OwnerUserID = "c5955b95-5492-4c7b-a3cb-c749c85e3a16",
                            ResolutionId = 3,
                            Resolved = false
                        },
                        new
                        {
                            FeedbackRequestId = 19,
                            Accepted = false,
                            CreationDate = new DateTime(2022, 10, 5, 20, 16, 37, 620, DateTimeKind.Local).AddTicks(2112),
                            Description = "",
                            ESignature = "",
                            OwnerUserID = "5559d343-5062-4cd1-b0ae-25301e70a10d",
                            ResolutionId = 3,
                            Resolved = false
                        });
                });

            modelBuilder.Entity("ResolutionManagement.Models.Resolution", b =>
                {
                    b.Property<int?>("ResolutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("ResolutionId"), 1L, 1);

                    b.Property<string>("Abstract")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OwnerUserID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResolutionId");

                    b.ToTable("Resolution", (string)null);

                    b.HasData(
                        new
                        {
                            ResolutionId = 0,
                            Abstract = "",
                            CreationDate = new DateTime(2022, 10, 5, 20, 16, 37, 620, DateTimeKind.Local).AddTicks(1936),
                            OwnerUserID = "221fedc9-3ad4-492e-bfc0-20f198923a24",
                            Status = "in progress"
                        },
                        new
                        {
                            ResolutionId = 1,
                            Abstract = "",
                            CreationDate = new DateTime(2022, 10, 5, 20, 16, 37, 620, DateTimeKind.Local).AddTicks(1981),
                            OwnerUserID = "221fedc9-3ad4-492e-bfc0-20f198923a24",
                            Status = "in progress"
                        },
                        new
                        {
                            ResolutionId = 2,
                            Abstract = "",
                            CreationDate = new DateTime(2022, 10, 5, 20, 16, 37, 620, DateTimeKind.Local).AddTicks(1983),
                            OwnerUserID = "37c1ba03-d67c-437e-ac19-2b38b123c55a",
                            Status = "in progress"
                        },
                        new
                        {
                            ResolutionId = 3,
                            Abstract = "",
                            CreationDate = new DateTime(2022, 10, 5, 20, 16, 37, 620, DateTimeKind.Local).AddTicks(1986),
                            OwnerUserID = "5559d343-5062-4cd1-b0ae-25301e70a10d",
                            Status = "in progress"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ResolutionManagement.Models.FeedbackRequest", b =>
                {
                    b.HasOne("ResolutionManagement.Models.Resolution", "Resolution")
                        .WithMany()
                        .HasForeignKey("ResolutionId");

                    b.Navigation("Resolution");
                });
#pragma warning restore 612, 618
        }
    }
}
